name = "katla-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "katla-base"
database_id = "a073a463-3439-48f7-8905-a238dcd11c81"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "katla-assets"

[vars]
CORS_ORIGIN = "https://katlagroup.com"
